version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio-data:/data

  create-bucket:
    image: minio/mc:RELEASE.2024-09-22T00-00-00Z
    depends_on: [minio]
    entrypoint: >-
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${MINIO_BUCKET} || true &&
      mc anonymous set download local/${MINIO_BUCKET} || true &&
      sleep 2 && echo 'Bucket ready' "

  airflow:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
      _PIP_ADDITIONAL_REQUIREMENTS: "boto3 structlog prometheus-client pyarrow pandas"
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./infra/airflow/plugins:/opt/airflow/plugins
      - ./common:/opt/airflow/common
    ports: ["8080:8080"]
    command: bash -c "airflow db init && airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com && airflow webserver & airflow scheduler"

  metabase:
    image: metabase/metabase:v0.49.15
    ports: ["3000:3000"]

volumes:
  minio-data: