name: batch_project
version: 1.0.0
config-version: 2

profile: project_batch_warehouse
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  batch_project:
    +materialized: table
    staging:
      +schema: staging
      +materialized: table
    dims:
      +schema: dims
      +materialized: table