version: 2
models:
  - name: stg_taxi_trips
    description: Cleaned yellow taxi trips (typed, deduped, canonical columns)
    columns:
      - name: vendor_id
        tests: [not_null]
      - name: pickup_ts
        tests: [not_null]
      - name: dropoff_ts
        tests: [not_null]
      - name: pu_location_id
        tests: [not_null]
      - name: do_location_id
        tests: [not_null]
      - name: payment_type
        tests:
          - accepted_values:
              values: [1,2,3,4,5,6]