name: ci
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install --upgrade pip
      - run: pip install ruff black mypy pytest structlog prometheus-client boto3 pyarrow pandas requests pytest-cov pre-commit
      - run: pre-commit run --all-files
      - name: Run tests with coverage
        run: pytest -q --cov=./ --cov-report=xml:coverage.xml --cov-report=html
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml