name: Coverage

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install --upgrade pip
          pip install ruff black mypy pytest structlog prometheus-client boto3 pyarrow pandas requests pytest-cov pre-commit
          pytest -q --cov=./ --cov-report=xml:coverage.xml --cov-report=html
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

  report:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .
      - name: Create test coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
